/*!
 * Lampa Plugin Installer — auto-generated by scripts/pack-installer.sh
 * Generated: 2026-04-22T17:12:01Z
 *
 * Add this ONE URL to Lampa (Настройки → Расширения → Добавить плагин) on your
 * TV. On every app start, idempotently ensures the bundled plugin URLs are in
 * the 'plugins' list. Reloads Lampa ONLY if something was actually added — so
 * on steady state it's a silent no-op.
 *
 * Keep the installer installed on TV long-term — it lets you change the bundle
 * by pushing a new plugins/installer.js; TV picks up the new targets on next
 * Lampa start. No re-installation needed.
 *
 * Bundled this run:
 *   - https://vahagn-99.github.io/lampa/plugins/lazy-resume-probe.js
 *   - https://vahagn-99.github.io/lampa/plugins/log-collector.js
 *
 * Regenerate by re-running scripts/pack-installer.sh with different args.
 *
 * Log prefix:   [LampaInstaller]
 * Global guard: window.__lampaPluginInstallerLoaded
 */
(function () {
    'use strict';

    if (window.__lampaPluginInstallerLoaded) return;
    window.__lampaPluginInstallerLoaded = true;

    var TARGETS       = ["https://vahagn-99.github.io/lampa/plugins/lazy-resume-probe.js","https://vahagn-99.github.io/lampa/plugins/log-collector.js"];
    var RELOAD_DELAY  = 3000;
    var NOTY_MS       = 3500;

    function log(msg) { try { console.log('[LampaInstaller]', msg); } catch (e) {} }

    function notify(msg) {
        try { if (window.Lampa && Lampa.Noty && Lampa.Noty.show) Lampa.Noty.show(msg, { time: NOTY_MS }); } catch (e) {}
        log(msg);
    }

    function ensureInstalled() {
        try {
            var raw = localStorage.getItem('plugins') || '[]';
            var list;
            try { list = JSON.parse(raw); } catch (e) { list = []; }
            if (!list || list.constructor !== Array) list = [];

            var seen = {};
            for (var i = 0; i < list.length; i++) {
                if (list[i] && list[i].url) seen[list[i].url] = true;
            }

            var added = 0;
            for (var j = 0; j < TARGETS.length; j++) {
                if (!seen[TARGETS[j]]) {
                    list.push({ url: TARGETS[j], status: true });
                    seen[TARGETS[j]] = true;
                    added++;
                }
            }

            if (added === 0) {
                log('bundle already installed, nothing to do');
                return;
            }

            localStorage.setItem('plugins', JSON.stringify(list));
            notify('[Installer] +' + added + ' plugin' + (added === 1 ? '' : 's') + '. Reloading...');

            setTimeout(function () {
                try { window.location.reload(); } catch (e) {}
            }, RELOAD_DELAY);
        } catch (err) {
            try { console.error('[LampaInstaller]', err); } catch (e) {}
        }
    }

    if (window.Lampa && Lampa.Listener) {
        Lampa.Listener.follow('app', function (e) { if (e && e.type === 'ready') ensureInstalled(); });
        setTimeout(ensureInstalled, 1500);
    } else {
        var ri = setInterval(function () {
            if (window.Lampa && Lampa.Listener) {
                clearInterval(ri);
                Lampa.Listener.follow('app', function (e) { if (e && e.type === 'ready') ensureInstalled(); });
                setTimeout(ensureInstalled, 1500);
            }
        }, 300);
    }
})();
